name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm run update
      - run: npm i
      - run: npm run build

      # Commit and push the changes to the main branch
      - name: Commit changes
        run: |
          git config --global user.email mnpcmw6444@gmail.com
          git config --global user.name Action
          git add -A
          git commit -m "Build artifacts"
          git push

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
